### ISSUE TITLE
decide what data to collect

### ISSUE THREAD

**Issue by Kiki-Jiji** [WMDA/social-media-analysis#17]
Before we start the data ingest we need to know what data to actually collect! 

I put a guide in the [wiki](https://github.com/WMDA/social-media-analysis/wiki) to how to collect the available attributes.

**Comment by Kiki-Jiji** [comment]
# Data

Currently we collect
```python
topics_dict = {     "title":[], \
                        "score":[], \
                        "id":[], "url":[], \
                        "comms_num": [], \
                        "created": [], \
                        "body":[], \
                        "subreddit": []
                  } 
```
* Do we want the comment? If so we can need to collect the submissions `CommentForest` object and then iterate over it
* Do we want the author? If so need the `redditor` object and collect data from there (probably just id)
* NSFW?

**Comment by Daniel-Halls** [comment]
Ideally we want title, score, body, subreddit. ID alone will be useful as not actually that interested in the exact usersname rather just to check it is from a different user. Created is useful for characterising and checking for duplicates but otherwise not really useful. 

Ideally we also want all the comments posted on the submission including the NSFW.
